### ISSUE TITLE
Collections not shown in Twig

### ISSUE THREAD

**Issue by milosa** [bolt/core#1452]
Collections are not printed in the Twig templates.

When trying [this example](https://docs.bolt.cm/4.0/fields/collection#example-usage-in-templates), the loop doesn't print anything.

Also, I noticed that when I print `features|length` in twig, I get some weird numbers.
I added 1 feature in the back end, so I’d expect it to print 1. But instead I got 4.
When I add another one, it should be 2, or maybe 8, but I got 11.

Even though `features` has elements (because it's length > 0), the stuff inside the loop doesn’t get executed.

Maybe it's related to #1438 or the fact that `htmllang()` is still empty and therefore the system doesn't know which translation to use (#1437)

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.0 RC 23
| Install type                   |  Composer install
| PHP version                 | 7.4.6
| Web server                  | Symfony

Reproduction
------------

Create new Bolt project. Add field to a contenttype from [this example](https://docs.bolt.cm/4.0/fields/collection#example-usage-in-templates) and use the for loop from that page as well.

### Steps to reproduce

Add some data to the features field.

### Expected result

Features are shown on the page with the for loop from the docs.

### Actual result

Features are not shown.

**Comment by I-Valchev** [comment]
hey @milosa the PR I mentioned above should resolve the `|length` issue. This should resolve it, if not let me know :-)

**Comment by milosa** [comment]
@I-Valchev The length is now correct. The for loop still doesn't print anything though.

**Comment by milosa** [comment]
I'm not sure if you're aware, but for me, the `htmllang()` is still empty. #1439
I have a feeling this might be related to this issue somehow.

**Comment by milosa** [comment]
@bobdenotter #1455 only fixes the `|length` part of this issue, right?

**Comment by bobdenotter** [comment]
Re-opened.

**Comment by benplummer** [comment]
I'm having the same problem with `imagelist`.

It works fine when retrieving the first image in a template e.g. `{{ apartment | image | thumbnail(320, 240) }}`

However, when I try to loop through the `imagelist` to display each image, the for loop does not seem to run. It seems as though the `imagelist` is empty.

**Comment by bobdenotter** [comment]
I've updated the docs for this: https://github.com/bolt/docs/pull/1048

PR with code changes to follow shortly.

**Comment by bobdenotter** [comment]
@benplummer Latest commit to #1485 also fixes it for Imagelists.

**Comment by benplummer** [comment]
@bobdenotter Thanks!
