### ISSUE TITLE
Sidebar is empty

### ISSUE THREAD

**Issue by simonmnt** [bolt/core#2768]
A brief description of the issue goes here.

Details
-------

| Question                      | Answer
|----------------- | ------
| Relevant Bolt Version | 4.2.1
| Install type                   |  Composer install
| PHP version                 | 7.4.10 |
| Web server                  | Apache
| For UX/UI issues        | Chrome

### Bug summary

Hi, I don't know why, but sidebar menu is empty.

![Capture d’écran 2021-08-12 à 16 07 39](https://user-images.githubusercontent.com/1232756/129212100-b0d4f0d5-8bea-47bc-8919-991f8b9a70ac.png)

DOM HTML

``` html
<div class="admin__sidebar admin__sidebar--is-collapsed">
        <div class="sidebar sidebar--sticky" id="bolt--sidebar">
            <admin-sidebar :menu="[{&quot;name&quot;:&quot;Tableau de bord&quot;,&quot;singular_name&quot;:null,&quot;slug&quot;:null,&quot;singular_slug&quot;:null,&quot;icon&quot;:&quot;fa-tachometer-alt&quot;,&quot;link&quot;:&quot;\/bolt\/&quot;,&quot;link_new&quot;:null,&quot;singleton&quot;:null,&quot;type&quot;:null,&quot;active&quot;:null,&quot;submenu&quot;:null},{&quot;name&quot;:&quot;Contenu&quot;,&quot;singular_name&quot;:null,&quot;slug&quot;:null,&quot;singular_slug&quot;:null,&quot;icon&quot;:&quot;fa-file&quot;,&quot;link&quot;:null,&quot;link_new&quot;:null,&quot;singleton&quot;:null,&quot;type&quot;:&quot;separator&quot;,&quot;active&quot;:null,&quot;submenu&quot;:null},{&quot;name&quot;:&quot;Accueil&quot;,&quot;singular_name&quot;:&quot;accueil&quot;,&quot;slug&quot;:&quot;accueil&quot;,&quot;singular_slug&quot;:&quot;accueil&quot;,&quot;icon&quot;:&quot;fa-home&quot;,&quot;link&quot;:&quot;\/bolt\/content\/accueil&quot;,&quot;link_new&quot;:&quot;\/bolt\/new\/accueil&quot;,&quot;singleton&quot;:true,&quot;type&quot;:null,&quot;active&quot;:false,&quot;submenu&quot;:[]},{&quot;name&quot;:&quot;Pages&quot;,&quot;singular_name&quot;:&quot;Page&quot;,&quot;slug&quot;:&quot;pages&quot;,&quot;singular_slug&quot;:&quot;page&quot;,&quot;icon&quot;:&quot;fa-copy&quot;,&quot;link&quot;:&quot;\/bolt\/content\/pages&quot;,&quot;link_new&quot;:&quot;\/bolt\/new\/pages&quot;,&quot;singleton&quot;:false,&quot;type&quot;:null,&quot;active&quot;:true,&quot;submenu&quot;:[{&quot;id&quot;:3,&quot;name&quot;:&quot;BOPS64, sp\u00e9cialiste de la cimentation et de la stimulation de puits&quot;,&quot;link&quot;:&quot;\/page\/bops64-specialiste-de-la-cimentation-et-de-la-stimulation-de-puits&quot;,&quot;editLink&quot;:&quot;\/bolt\/edit\/3&quot;,&quot;icon&quot;:&quot;fa-file&quot;},{&quot;id&quot;:16,&quot;name&quot;:&quot;Nos r\u00e9alisations&quot;,&quot;link&quot;:&quot;\/page\/nos-realisations&quot;,&quot;editLink&quot;:&quot;\/bolt\/edit\/16&quot;,&quot;icon&quot;:&quot;fa-file&quot;},{&quot;id&quot;:14,&quot;name&quot;:&quot;Les \u00e9quipements&quot;,&quot;link&quot;:&quot;\/page\/les-equipements&quot;,&quot;editLink&quot;:&quot;\/bolt\/edit\/14&quot;,&quot;icon&quot;:&quot;fa-file&quot;},{&quot;id&quot;:13,&quot;name&quot;:&quot;Le laboratoire&quot;,&quot;link&quot;:&quot;\/page\/le-laboratoire&quot;,&quot;editLink&quot;:&quot;\/bolt\/edit\/13&quot;,&quot;icon&quot;:&quot;fa-file&quot;},{&quot;id&quot;:7,&quot;name&quot;:&quot;Mentions l\u00e9gales&quot;,&quot;link&quot;:&quot;\/page\/mentions-legales&quot;,&quot;editLink&quot;:&quot;\/bolt\/edit\/7&quot;,&quot;icon&quot;:&quot;fa-file&quot;}]},{&quot;name&quot;:&quot;Param\u00e8tres&quot;,&quot;singular_name&quot;:null,&quot;slug&quot;:null,&quot;singular_slug&quot;:null,&quot;icon&quot;:&quot;fa-wrench&quot;,&quot;link&quot;:null,&quot;link_new&quot;:null,&quot;singleton&quot;:null,&quot;type&quot;:&quot;separator&quot;,&quot;active&quot;:null,&quot;submenu&quot;:null},{&quot;name&quot;:&quot;Configuration&quot;,&quot;singular_name&quot;:null,&quot;slug&quot;:&quot;configuration&quot;,&quot;singular_slug&quot;:null,&quot;icon&quot;:&quot;fa-sliders-h&quot;,&quot;link&quot;:&quot;\/bolt\/menu\/configuration&quot;,&quot;link_new&quot;:null,&quot;singleton&quot;:null,&quot;type&quot;:null,&quot;active&quot;:null,&quot;submenu&quot;:[{&quot;name&quot;:&quot;Utilisateurs &amp; Permissions&quot;,&quot;icon&quot;:&quot;fa-users&quot;,&quot;editLink&quot;:&quot;\/bolt\/users&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Configuration principale&quot;,&quot;icon&quot;:&quot;fa-cog&quot;,&quot;editLink&quot;:&quot;\/bolt\/file-edit\/config?file=\/bolt\/config.yaml&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Type de contenu&quot;,&quot;icon&quot;:&quot;fa-object-group&quot;,&quot;editLink&quot;:&quot;\/bolt\/file-edit\/config?file=\/bolt\/contenttypes.yaml&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Taxonomies&quot;,&quot;icon&quot;:&quot;fa-tags&quot;,&quot;editLink&quot;:&quot;\/bolt\/file-edit\/config?file=\/bolt\/taxonomy.yaml&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Param\u00e8tres du menu&quot;,&quot;icon&quot;:&quot;fa-list&quot;,&quot;editLink&quot;:&quot;\/bolt\/file-edit\/config?file=\/bolt\/menu.yaml&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Configuration du routage&quot;,&quot;icon&quot;:&quot;fa-directions&quot;,&quot;editLink&quot;:&quot;\/bolt\/file-edit\/config?file=\/routes.yaml&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Tous les fichiers de configuration&quot;,&quot;icon&quot;:&quot;fa-cogs&quot;,&quot;editLink&quot;:&quot;\/bolt\/filemanager\/config&quot;,&quot;active&quot;:null}]},{&quot;name&quot;:&quot;Maintenance&quot;,&quot;singular_name&quot;:null,&quot;slug&quot;:&quot;maintenance&quot;,&quot;singular_slug&quot;:null,&quot;icon&quot;:&quot;fa-tools&quot;,&quot;link&quot;:&quot;\/bolt\/menu\/maintenance&quot;,&quot;link_new&quot;:null,&quot;singleton&quot;:null,&quot;type&quot;:null,&quot;active&quot;:null,&quot;submenu&quot;:[{&quot;name&quot;:&quot;Extensions&quot;,&quot;icon&quot;:&quot;fa-plug&quot;,&quot;editLink&quot;:&quot;\/bolt\/extensions&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Logs&quot;,&quot;icon&quot;:&quot;fa-clipboard&quot;,&quot;editLink&quot;:&quot;\/bolt\/logviewer&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;API&quot;,&quot;icon&quot;:&quot;fa-code&quot;,&quot;editLink&quot;:&quot;\/bolt\/api&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Vider le cache&quot;,&quot;icon&quot;:&quot;fa-eraser&quot;,&quot;editLink&quot;:&quot;\/bolt\/clearcache&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Traductions&quot;,&quot;icon&quot;:&quot;fa-language&quot;,&quot;editLink&quot;:&quot;\/bolt\/_trans&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;\u00c0 propos de Bolt&quot;,&quot;icon&quot;:&quot;fa-award&quot;,&quot;editLink&quot;:&quot;\/bolt\/about&quot;,&quot;active&quot;:null}]},{&quot;name&quot;:&quot;Gestion de fichiers&quot;,&quot;singular_name&quot;:null,&quot;slug&quot;:&quot;filemanagement&quot;,&quot;singular_slug&quot;:null,&quot;icon&quot;:&quot;fa-folder-open&quot;,&quot;link&quot;:&quot;\/bolt\/menu\/filemanagement&quot;,&quot;link_new&quot;:null,&quot;singleton&quot;:null,&quot;type&quot;:null,&quot;active&quot;:null,&quot;submenu&quot;:[{&quot;name&quot;:&quot;Fichiers t\u00e9l\u00e9charg\u00e9s&quot;,&quot;icon&quot;:&quot;fa-archive&quot;,&quot;editLink&quot;:&quot;\/bolt\/filemanager\/files&quot;,&quot;active&quot;:null},{&quot;name&quot;:&quot;Afficher et modifier les mod\u00e8les&quot;,&quot;icon&quot;:&quot;fa-scroll&quot;,&quot;editLink&quot;:&quot;\/bolt\/filemanager\/themes&quot;,&quot;active&quot;:null}]}]" :version="'4.2.1'" :about-link="&quot;\/bolt\/about&quot;" :labels="{&quot;toggler&quot;:&quot;Basculer la largeur de la barre lat\u00e9rale&quot;,&quot;action.new&quot;:&quot;Nouveau&quot;,&quot;action.view&quot;:&quot;Vue&quot;}"></admin-sidebar>
        </div>
    </div>
```

**Comment by simonmnt** [comment]
@nestordedios It's weird, same project in local and production. locally it's works, i don't know why. I'm using bolt/project

**Comment by bobdenotter** [comment]
Try this: 

1. Make sure you copy the assets from the update: `bin/console bolt:copy-assets`
2. Clear the cache: `bin/console cache:clear` 

Are they still not showing up?

**Comment by simonmnt** [comment]
Thanks @bobdenotter , 

Is composer post install command who launch this script (' Bolt\ComposerScripts\ProjectEventHandler::postInstall') do bin/console bolt:copy-assets ?
I had an issue with my composer version in preprod, is now fixed !

**Comment by bobdenotter** [comment]
Yeah, it seems like there is/was a quirk there.. Should be fixed now that #2766 is merged in. :-)

**Comment by Deuchnord** [comment]
> Try this:
> 
>     1. Make sure you copy the assets from the update: `bin/console bolt:copy-assets`
> 
>     2. Clear the cache: `bin/console cache:clear`
> 
> 
> Are they still not showing up?

I have tried to do this as well, but this did not solve the issue on my side. The sidebar remains empty.
Also tried to delete the content of `/var/cache` folder, and to delete all the assets and regenerate them, without success :disappointed:

**Comment by bobdenotter** [comment]
Are you sure? For the cases i've seen it happen, that fixed it. .

What errors are you getting in the browser's inspector?

**Comment by Deuchnord** [comment]
Yes, I ran both commands, stopped and even destroyed all my Docker containers and restarted them, tried to clear the cache without warmup. The commands run without any error:

```
🚀 docker-compose exec bolt-php bin/console bolt:copy-assets    

 Installing Bolt assets as hard copies.

 --- -------- ---------------- 
      Folder   Method / Error  
 --- -------- ---------------- 
  ✔   assets   copied          
 --- -------- ---------------- 

                                                                                                                        
 [OK] All assets were successfully installed.                                                                           

🚀 docker-compose exec bolt-php bin/console cache:clear --no-warmup 

 // Clearing the cache for the dev environment with debug true
```

I have no error in the Inspector (tested on Firefox and Chromium), just the same weird `<admin-sidebar>` DOM element as described in #2771.

**Comment by nestordedios** [comment]
Thank you @bobdenotter ! 👍 

This worked for me https://github.com/bolt/core/issues/2768#issuecomment-898234945

It could be that some fields are not being rendered after you run those commands. 

Then running `bin/console ext:config --with-config` will fix it

**Comment by info-refactory** [comment]
For anyone stil having to deal with this: had the same issue, tried all suggested methods, no luck. At the end what worked for me was to keep assets at version `4.1.*`. So, currently running on `bolt/core 4.2.6` and `bolt/assets 4.1.23` and sidebar shows fine.
I'm sure I may be missing something (Docker is involved) but this solution is enough for me, as I'm planning to move to 5 anyway as soon as possible.
Thank you everyone for your code and your suggestions.
