### ISSUE TITLE
Saving Content without ajaxy_saving

### ISSUE THREAD

**Issue by Spomsoree** [bolt/core#3406]
While testing the 5.2 beta 11 I noticed that contents are created multiple times on save.

Details
-------

| Question                                              | Answer
|------------------------------------------------------ | ------
| Relevant Bolt Version                                 | 5.2 beta 11
| Install type                                          |  composer install
| PHP version                                           | 8.1
| Web server                                            | nginx

Reproduction
------------

Install bolt 5.2 beta 11 and save a new content element.

### Bug summary

After saving a new content, two of them are created.
This also happens to singleton types.
This happens on creating a new content, not on saving an existent one.

I can fix it by setting `ajaxy_saving` to `true` **and** removing the route check in the [_buttons.html.twig](https://github.com/bolt/core/blob/master/templates/content/_buttons.html.twig#L6) template.

`{% if app.request.get('_route') == 'bolt_content_edit' and config.get('general/ajaxy_saving') %}`

I'm not making a PR because this will still create two pages if `ajaxy_saving` is set to `false`.

### Specifics

Use /bolt/new/pages for example and create a new content.

### Expected result

Only one page should be created.

### Actual result

Two identical pages are created.

**Comment by Filoz** [comment]
Hi, 
I think the problem should be fixed by https://github.com/bolt/core/pull/3379

I think (maybe I'm wrong) that the assets are not in synch with that update.

**Comment by Spomsoree** [comment]
@Filoz I'll test this, but this does not fix the check on the `bolt_content_edit` route, right?

**Comment by Spomsoree** [comment]
@Filoz i tested it.

https://github.com/bolt/core/pull/3379 did not fix it for me.

**Comment by bobdenotter** [comment]
@Spomsoree Are you sure? I had the issue on beta 11, but the fix by @filoz resolved it for me.. 

Can you run `composer update`, and verify you have both `bolt/core` and `bolt/assets` 5.2.0 b12, and try again? 

<img width="784" alt="Scherm­afbeelding 2023-02-15 om 12 48 03" src="https://user-images.githubusercontent.com/1833361/219019350-ea915761-cfa6-40fc-bf23-258929f0a290.png">

**Comment by Spomsoree** [comment]
@bobdenotter you are right.

beta 5.2.0-beta.12 fixed the issue

**Comment by bobdenotter** [comment]
Excellent! Thanks for testing, both! :-)
